name: Faktory Build Workflow
on:
  workflow_call:

jobs:
  fixprbase:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github stuff
        run: echo "Event ${{ github.event_name }}"
#      - name: Check and fix PR Base
#        id: fix-pr-base
#        uses: touchlab-lab/fix-pr-base@v0.2
#        with:
#          githubToken: ${{ secrets.GITHUB_TOKEN }}
#          targetbranch: develop