name: Faktory Build Workflow
on:
  workflow_call:
    inputs:
      faktory_module:
        required: true
        type: string
      build_branch:
        required: true
        type: string
    secrets:
      FAKTORY_SECRET_KEY:
        required: true
      gradle_params:
        required: false

jobs:
#  logmystuff:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Echo github stuff
#        run: echo "Event github.event_name ${{ github.event_name }} github.event.action ${{ github.event.action }} github.repository ${{ github.repository }}"
  installationinfo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github stuff
        run: echo "Event github.event_name ${{ github.event_name }} github.event.action ${{ github.event.action }} github.repository ${{ github.repository }}"
      - name: Check and fix PR Base
        if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'synchronize')}}
        id: fix-pr-base
        uses: touchlab/fkaction-fix-pr-base@main
        with:
          FAKTORY_SECRET_KEY: ${{ secrets.FAKTORY_SECRET_KEY }}
          build_branch: ${{ inputs.build_branch }}
  call-iosbinary:
    uses: ./.github/workflows/iosbinary.yml
    with:
      faktory_module: ${{ inputs.faktory_module }}
      build_branch: ${{ inputs.build_branch }}
    secrets:
      FAKTORY_SECRET_KEY: ${{ secrets.FAKTORY_SECRET_KEY }}
      gradle_params: -PAWS_TOUCHLAB_ACCESS=${{ secrets.AWS_TOUCHLAB_ACCESS }} -PAWS_TOUCHLAB_PRIVATE=${{ secrets.AWS_TOUCHLAB_PRIVATE }}