name: Faktory Build Workflow
on:
  workflow_call:
    secrets:
      FAKTORY_SECRET_KEY:
        required: true
      gradle_params:
        required: false

jobs:
#  logmystuff:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Echo github stuff
#        run: echo "Event github.event_name ${{ github.event_name }} github.event.action ${{ github.event.action }} github.repository ${{ github.repository }}"
  iosbinary:
#    if: ${{ github.event_name == 'merge_group' }}
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Checksame read before
        id: checksamebefore
        uses: touchlab/fkaction-read-checksame@main
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache build tooling
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}
      - name: Run Check For Changes
        run: ./gradlew -PFAKTORY_SECRET_KEY=${{ secrets.FAKTORY_SECRET_KEY }} -Dorg.gradle.caching=true ${{ secrets.gradle_params }} checkIfChanges --no-daemon --stacktrace
      - name: Checksame read after
        id: checksameafter
        uses: touchlab/fkaction-read-checksame@main
      - name: Echo checksum reads
        run: echo "Checksum before ${{ steps.checksamebefore.outputs.checksum }} / Checksum after ${{ steps.checksameafter.outputs.checksum }}"
      - name: Native Tests
        if: ${{ steps.checksamebefore.outputs.checksum != steps.checksameafter.outputs.checksum }}
        run: ./gradlew -PFAKTORY_SECRET_KEY=${{ secrets.FAKTORY_SECRET_KEY }} -Dorg.gradle.caching=true ${{ secrets.gradle_params }} allNativeTests --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
      - name: Build Main
        if: ${{ steps.checksamebefore.outputs.checksum != steps.checksameafter.outputs.checksum }}
        run: ./gradlew -PFAKTORY_SECRET_KEY=${{ secrets.FAKTORY_SECRET_KEY }} -Dorg.gradle.caching=true ${{ secrets.gradle_params }} publishRemoteFramework --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
      - name: Push Config Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update iOS Packaging