name: Faktory Build Workflow
on:
  workflow_call:

jobs:
  fixprbase:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo github stuff
        run: echo "Event github.event_name ${{ github.event_name }} github.event.action ${{ github.event.action }} github.repository ${{ github.repository }}"
      - name: Check and fix PR Base
        id: fix-pr-base
        uses: touchlab-lab/fix-pr-base@v0.7
  iosbinary:
    if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
    runs-on: macos-latest
    steps:
      - name: Echo github stuff
        run: echo "Event github.event_name ${{ github.event_name }} github.ref_name ${{ github.ref_name }}"
      - name: Checkout the repo
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache build tooling
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
      - name: Cache spm
        uses: actions/cache@v2
        with:
          path: |
            */build
            .gradle
          key: ${{ runner.os }}-iosbinary-${{ steps.time.outputs.time }}
          restore-keys: |
            ${{ runner.os }}-iosbinary-
      - name: Build Main
        run: ./gradlew :api:uploadXCFramework --no-daemon --stacktrace
      - name: Push SPM Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update SPM remote
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

